### ISSUE TITLE
can you help me

### ISSUE THREAD

**Issue by leevinci** [lucaricciatl/continuum-control#1]
Hello,Your work is great， I run the workspace and main function to prompt me that there is no corresponding function，can you help me

**Comment by lucaricciatl** [comment]
Hi, thank you for your interest in my work,. I need some informations to help you
Wich file do you run? Wich function is not found?
Have you try to find that function in subfolders and add them to path?

**Comment by leevinci** [comment]
It was solved. I was careless and didn't import all the functions. After I Google, I solved the problem. By the way, you're a genius

**Comment by leevinci** [comment]
I am very interested in continuous manipulator. Recently, I saw two papers. I have mastered the principle, but I can't write the code of the paper. I wonder if you have found similar code during your research? Can you provide me a copy, or can you help me reproduce these two papers, or please give me some advice.




The corresponding information link is here:

Godage I S, Walker I D. Dual Quaternion based modal kinematics for multisection continuum arms[C]//2015 IEEE International Conference on Robotics and Automation (ICRA). IEEE, 2015: 1416-1422.；



Godage I S, Guglielmino E, Branson D T, et al. Novel modal approach for kinematics of multisection continuum arms[C]//2011 IEEE/RSJ International Conference on Intelligent Robots and Systems. IEEE, 2011: 1093-1098.

Novel modal approach for kinematics of multisection continuum arms；



https://www.youtube.com/watch?v=iMtOU1xuPnQ ； https://www.youtube.com/watch?v=vVl07veP0rI

**Comment by lucaricciatl** [comment]
Hi, I can actually share some code for kinematic and inverse kinematic. 
I created a new repo for IK here : https://github.com/ATLED-3301/soft_continuum_IK . I hope it can help you.

**Comment by leevinci** [comment]
[Inverse_kinematics_of_infrared_spectrum.zip](https://github.com/ATLED-3301/continuum---soft-robot/files/9098865/Inverse_kinematics_of_infrared_spectrum.zip)
This is my code, but I'm not very good at building Jacobian matrix. Can you give me some advice?

**Comment by lucaricciatl** [comment]
I noticed that you are running the algorithm using symbolic computation methods.
This degrades performance considerably.
I suggest calculating the Jacobian matrix numerically for each joint in the following way :

![Screenshot 2022-07-13 135022](https://user-images.githubusercontent.com/26041712/178727102-b3508dc5-2a93-476f-8c11-77f3b19b5b22.png)

And then using iterativelly: 

![Screenshot 2022-07-13 135431](https://user-images.githubusercontent.com/26041712/178727817-b924e39f-7cb4-457b-aa1b-250f57068eaf.png)

you can find the q that ensure that the tip position and orientation will reach the desired position and orientation.

**Comment by leevinci** [comment]
Dear：
How can i get the value of&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ATLED-3301/continuum---soft-robot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月13日(星期三) 晚上7:56
***@***.***&gt;;
抄送:&nbsp;"Li ***@***.******@***.***&gt;;
主题:&nbsp;Re: [ATLED-3301/continuum---soft-robot] can you help me (Issue #1)





 
I noticed that you are running the algorithm using symbolic computation methods.
 This degrades performance considerably.
 I suggest calculating the Jacobian matrix numerically for each joint in the following way :
 

 
 
And then using iterativelly:
 

 
you can find the q that ensure that the tip position and orientation will reach the desired position and orientation.
